compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmRegistryServer: https://pkgs.dev.azure.com/ITLabs-LLC/_packaging/WellCare360FETest/npm/registry
npmRegistries:
  //pkgs.dev.azure.com/ITLabs-LLC/_packaging/WellCare360FETest/npm/registry:
    npmAlwaysAuth: true
